export const COMBAT_RATE = 466
export const NON_COMBAT_RATE = 266
export const SPECIAL_NEEDS_COMPENSATION = 2000
export const MENTAL_HEALTH_COMPENSATION = 1500
export const FAMILY_CARE_COMPENSATION = 1500
export const EXTRA_DAYS_COMPENSATION = 300
export const GRANT_DAILY_RATE = 133
